encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.view_entry, name="view-entry"),
    path("search", views.search, name="search"),
    path("new-entry", views.write_entry, name="new-entry"),
    path("edit-entry/<str:title>", views.edit_entry, name="edit-entry"),
    path("rand-entry/", views.get_random_entry, name="rand-entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.core.files.storage import default_storage
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms

from markdown2 import markdown
import re
from random import randint

from . import util


class NewEntryForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Entry Title"}))
    content = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "Write content in Markdown syntax"}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def view_entry(request, title):
    if util.get_entry(title) == None:
        return render(request, "encyclopedia/request_not_found.html", 
                {"title": title})
    else:
        entry_data = markdown(util.get_entry(title))
        return render(request, "encyclopedia/view_entry.html", 
                    {"entry_data": entry_data,
                    "title": title})

def search(request):
    _, filenames = default_storage.listdir("entries")
    available_entries = list(sorted(re.sub(r"\.md$", "", filename)
                            for filename in filenames if filename.endswith(".md")))
    for entry in available_entries:
        title = str.lower(request.POST.get("query"))
        if title == str.lower(entry):
            return HttpResponseRedirect(reverse("encyclopedia:view_entry", args=(title,)))
        else:
            regexp = re.compile(title)
            matches = []
            for entry in available_entries:
                if regexp.search(str.lower(entry)):
                    matches.append(entry)

            return render(request, "encyclopedia/search_results.html", 
                        {"matches": matches, "title": title})

def write_entry(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("encyclopedia:view-entry", args=(title,)))
        else:
            return render(request, "encyclopedia/write_entry.html",
                        {"form": form})
    else:
        form = NewEntryForm()
        return render(request, "encyclopedia/write_entry.html",
                    {"form": form})

def edit_entry(request, title):
    content = util.get_entry(title.strip())
    form = NewEntryForm()
    form.content = content
    form.title = title
    return render(request, "encyclopedia/edit_entry.html", 
            {"content": content, "title": title})

def get_random_entry(request):
    entries = util.list_entries()
    rand_idx = randint(0, len(entries) - 1)
    return HttpResponseRedirect(reverse("encyclopedia:view-entry", args=(entries[rand_idx],)))

encyclopedia/templates/encyclopedia/edit_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry
{% endblock %}

{% block body %}
    <h1>Edit {{title}}</h1>

    <form action="{% url 'encyclopedia:new-entry' %}" method="POST">
        {% csrf_token %}
        <textarea class="form-control" name="title" id="">
            {{ title }}
        </textarea>

        <br>
        <textarea class="form-control" name="content">
            {{ content }}
        </textarea>
        <br><br>
        <button type="submit" class="btn-floating blue waves-effect waves-dark right">
            <i class="material-icons">add</i>
        </button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:view-entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/css/styles.css' %}" rel="stylesheet"> -->

        <link rel="stylesheet" type="text/css" href="{% static './encyclopedia/css/icons.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static './encyclopedia/css/layout.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static './encyclopedia/css/fonts.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static './encyclopedia/css/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static './encyclopedia/css/materialize/materialize.min.css' %}"/>
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="query" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new-entry' %}">Create New Entry</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:rand-entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

        <script type="text/javascript" src="{% static './encyclopedia/js/jquery-3.5.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static './encyclopedia/js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static './encyclopedia/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

encyclopedia/templates/encyclopedia/request_not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    404 - Not Found
{% endblock %}

{% block body %}
    There's no entry with the title "{{title}}"
{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}

    <h1>Search Results for "{{title}}"</h1>
    <ul>
        {% for match in matches %}
            <li><a href="{% url 'encyclopedia:view-entry' match %}">{{ match }}</a></li>
        {% empty %}
            No Matches found for "{{title}}"
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/view_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

    {{ entry_data | safe }}

    <hr>

    <button class="btn-floating orange waves-effect waves-dark right">
        <a href="{% url 'encyclopedia:edit-entry' title %}"><i class="material-icons">edit</i></a>
    </button>
{% endblock %}

encyclopedia/templates/encyclopedia/write_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    <h1>Create a new entry</h1>

    <form action="{% url 'encyclopedia:new-entry' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <br><br>
        <button type="submit" class="btn-floating blue waves-effect waves-dark right">
            <i class="material-icons">add</i>
        </button>
    </form>
{% endblock %}